spring.application.name=libreria
#confijuracion de conexion
spring.datasource.url=jdbc:mysql://localhost:3306/dblibreria2?uSSL=false&serverTimeZone=UTC
spring.datasource.username=root
spring.datasource.password=root

#dialecto de MYSQL
#spring.jpa.database-plataform=org.hibernate.dialect.MySQL8Dialect

#Esquema
spring.jpa.hibernate.ddl-auto=update

#mostrar en consola
spring.jpa.shou-sql=true
spring.jpa.properties.hibernate.format_sql=true
#driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
